alias aa='add_alias'
alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -lah'
alias andrlint='arc lint --engine FBAndroidFullLintEngine'
alias bb='mybuck build'
alias bbf='mybuck build fb4a'
alias bi='mybuck install'
alias bt='mybuck test'
alias cdfba='cd ~/fbandroid/'
alias kx='killall -9 Xcode'
alias dfb4a='adb shell am start -D -n com.facebook.wakizashi/com.facebook.katana.LoginActivity'
alias adbres='adb kill-server; sleep 5; adb start-server;'
alias cd..='cd ..'
alias rm='rm -i'
alias cp='cp --backup=numbered'
alias ln='ln --backup=numbered'
alias mv='mv -f --backup=numbered'
alias aas='source ~/.bash_aliases'
alias g='git'
alias bifb4a='pushd /Users/bel/fbandroid; buck install fb4a; popd;'
alias cdasdk='cd /Users/bel/fbsdkandroid'
alias cdhb4a='cd /Users/bel/fbsdkandroid/internal/testing/hb4a/'
alias gco='git checkout'
alias gcm='git checkout master'
alias gmrb='git rebase origin/master'
alias grepall='grep -rn . -e'
alias bis='bi --serial'
